	const_def

	const ENGINE_VS_SEEKER

	const ENGINE_DAYCARE_MAN_HAS_EGG
	const ENGINE_DAYCARE_MAN_HAS_MON
	const ENGINE_DAYCARE_LADY_HAS_MON

	const ENGINE_MOM_SAVING_MONEY ; $8
	const ENGINE_DST

	const ENGINE_POKEDEX
	const ENGINE_UNOWN_DEX
	const ENGINE_POKERUS
	const ENGINE_ROCKET_SIGNAL_ON_CH20
	const ENGINE_CREDITS_SKIP
	const ENGINE_BUG_CONTEST_ON
	const ENGINE_ROCKETS_IN_RADIO_TOWER ; $10
	const ENGINE_SAFARI_GAME
	const ENGINE_BUG_CONTEST_TIMER
	const ENGINE_SEEN_SHAMOUTI_ISLAND
	const ENGINE_BIKE_SHOP_CALL_ENABLED
	const ENGINE_GIVE_POKERUS
	const ENGINE_EXORCISED_LAV_RADIO_TOWER
	const ENGINE_ROCKETS_IN_MAHOGANY

	const ENGINE_STRENGTH_ACTIVE ; $18
	const ENGINE_ALWAYS_ON_BIKE
	const ENGINE_DOWNHILL

	const ENGINE_ZEPHYRBADGE
	const ENGINE_HIVEBADGE
	const ENGINE_PLAINBADGE
	const ENGINE_FOGBADGE
	const ENGINE_MINERALBADGE
	const ENGINE_STORMBADGE ; $20
	const ENGINE_GLACIERBADGE
	const ENGINE_RISINGBADGE

	const ENGINE_BOULDERBADGE
	const ENGINE_CASCADEBADGE
	const ENGINE_THUNDERBADGE
	const ENGINE_RAINBOWBADGE
	const ENGINE_MARSHBADGE
	const ENGINE_SOULBADGE ; $28
	const ENGINE_VOLCANOBADGE
	const ENGINE_EARTHBADGE

	const ENGINE_FLYPOINT_KRISS_HOUSE
	const ENGINE_FLYPOINT_PALLET
	const ENGINE_FLYPOINT_VIRIDIAN
	const ENGINE_FLYPOINT_PEWTER
	const ENGINE_FLYPOINT_MT_MOON
	const ENGINE_FLYPOINT_CERULEAN ; $30
	const ENGINE_FLYPOINT_ROCK_TUNNEL
	const ENGINE_FLYPOINT_VERMILION
	const ENGINE_FLYPOINT_LAVENDER
	const ENGINE_FLYPOINT_SAFFRON
	const ENGINE_FLYPOINT_CELADON
	const ENGINE_FLYPOINT_FUCHSIA
	const ENGINE_FLYPOINT_CINNABAR
	const ENGINE_FLYPOINT_INDIGO_PLATEAU ; $38
	const ENGINE_FLYPOINT_NEW_BARK
	const ENGINE_FLYPOINT_CHERRYGROVE
	const ENGINE_FLYPOINT_VIOLET
	const ENGINE_FLYPOINT_UNION_CAVE
	const ENGINE_FLYPOINT_AZALEA
	const ENGINE_FLYPOINT_CIANWOOD
	const ENGINE_FLYPOINT_GOLDENROD
	const ENGINE_FLYPOINT_OLIVINE ; $40
	const ENGINE_FLYPOINT_ECRUTEAK
	const ENGINE_FLYPOINT_MAHOGANY
	const ENGINE_FLYPOINT_LAKE_OF_RAGE
	const ENGINE_FLYPOINT_BLACKTHORN
	const ENGINE_FLYPOINT_SILVER_CAVE

	const ENGINE_LUCKY_NUMBER_SHOW

	const ENGINE_DAILY_BUG_CONTEST ; $48
	const ENGINE_SPECIAL_WILDDATA
	const ENGINE_ALL_FRUIT_TREES
	const ENGINE_WOBBUFFET_GIVEN
	const ENGINE_GOLDENROD_UNDERGROUND_MERCHANT_CLOSED
	const ENGINE_TEA_IN_BLUES_HOUSE

	const ENGINE_ALL_HIDDEN_GROTTOES

	const ENGINE_GAME_TIMER_PAUSE

	const ENGINE_PLAYER_IS_FEMALE
	const ENGINE_KRIS_IN_CABLE_CLUB

	const ENGINE_HAVE_EXAMINED_GS_BALL
	const ENGINE_HAVE_SILPHSCOPE
	const ENGINE_HAVE_SHINY_CHARM

	const ENGINE_GOLDENROD_DEPT_STORE_SALE_IS_ON

	const ENGINE_DUNSPARCE_SWARM
	const ENGINE_YANMA_SWARM

	const ENGINE_JACK
	const ENGINE_HUEY
	const ENGINE_GAVEN
	const ENGINE_BETH
	const ENGINE_JOSE ; $80
	const ENGINE_REENA
	const ENGINE_JOEY
	const ENGINE_WADE
	const ENGINE_RALPH
	const ENGINE_LIZ
	const ENGINE_ANTHONY
	const ENGINE_TODD
	const ENGINE_GINA ; $88
	const ENGINE_ARNIE
	const ENGINE_ALAN
	const ENGINE_DANA
	const ENGINE_CHAD
	const ENGINE_TULLY
	const ENGINE_BRENT
	const ENGINE_TIFFANY
	const ENGINE_VANCE ; $90
	const ENGINE_WILTON
	const ENGINE_PARRY
	const ENGINE_ERIN

	const ENGINE_BEVERLY_HAS_NUGGET
	const ENGINE_JOSE_HAS_STAR_PIECE
	const ENGINE_WADE_HAS_ITEM
	const ENGINE_GINA_HAS_LEAF_STONE
	const ENGINE_ALAN_HAS_FIRE_STONE ; $98
	const ENGINE_DANA_HAS_THUNDERSTONE
	const ENGINE_DEREK_HAS_NUGGET
	const ENGINE_TULLY_HAS_WATER_STONE
	const ENGINE_TIFFANY_HAS_PINK_BOW
	const ENGINE_WILTON_HAS_ITEM

	const ENGINE_JACK_MONDAY_MORNING
	const ENGINE_HUEY_WEDNESDAY_NIGHT
	const ENGINE_GAVEN_THURSDAY_MORNING ; $a0
	const ENGINE_BETH_FRIDAY_AFTERNOON
	const ENGINE_JOSE_SATURDAY_NIGHT
	const ENGINE_REENA_SUNDAY_MORNING
	const ENGINE_JOEY_MONDAY_AFTERNOON
	const ENGINE_WADE_TUESDAY_NIGHT
	const ENGINE_RALPH_WEDNESDAY_MORNING
	const ENGINE_LIZ_THURSDAY_AFTERNOON
	const ENGINE_ANTHONY_FRIDAY_NIGHT ; $a8
	const ENGINE_TODD_SATURDAY_MORNING
	const ENGINE_GINA_SUNDAY_AFTERNOON
	const ENGINE_ARNIE_TUESDAY_MORNING
	const ENGINE_ALAN_WEDNESDAY_AFTERNOON
	const ENGINE_DANA_THURSDAY_NIGHT
	const ENGINE_CHAD_FRIDAY_MORNING
	const ENGINE_TULLY_SUNDAY_NIGHT
	const ENGINE_BRENT_MONDAY_MORNING ; $b0
	const ENGINE_TIFFANY_TUESDAY_AFTERNOON
	const ENGINE_VANCE_WEDNESDAY_NIGHT
	const ENGINE_WILTON_THRUSDAY_MORNING
	const ENGINE_PARRY_FRIDAY_AFTERNOON
	const ENGINE_ERIN_SATURDAY_NIGHT

NUM_ENGINE_FLAGS EQU const_value
