	const_def
	const MUSIC_NONE                           ; 00
	const MUSIC_INTRO_BATTLE                   ; 01
	const MUSIC_TITLE_SCREEN                   ; 02
	const MUSIC_PALLET_TOWN                    ; 03
	const MUSIC_MEET_PROF_OAK                  ; 04
	const MUSIC_OAKS_LAB                       ; 05
	const MUSIC_MEET_RIVAL                     ; 06
	const MUSIC_FAREWELL_RIVAL                 ; 07
	const MUSIC_ROUTES1                        ; 08
	const MUSIC_WILD_BATTLE                    ; 09
	const MUSIC_DEFEATED_WILD_MON              ; 0a
	const MUSIC_CAPTURE                        ; 0b ; TODO: adapt pokered's SFX_CAUGHT_MON
	const MUSIC_CITIES1                        ; 0c
	const MUSIC_POKECENTER                     ; 0d
	const MUSIC_PKMN_HEALED                    ; 0e
	const MUSIC_DUNGEON2                       ; 0f
	const MUSIC_MUSEUM_GUY                     ; 10
	const MUSIC_MEET_FEMALE_TRAINER            ; 11
	const MUSIC_TRAINER_BATTLE                 ; 12
	const MUSIC_DEFEATED_TRAINER               ; 13
	const MUSIC_DUNGEON3                       ; 14
	const MUSIC_JESSIE_JAMES_ENCOUNTER         ; 15
	const MUSIC_MT_MOON_SQUARE                 ; 16
	const MUSIC_ROUTES3                        ; 17
	const MUSIC_CITIES2                        ; 18
	const MUSIC_GYM                            ; 19
	const MUSIC_ROUTES2                        ; 1a
	const MUSIC_JIGGLYPUFF_SONG                ; 1b
	const MUSIC_VERMILION                      ; 1c
	const MUSIC_SS_ANNE                        ; 1d
	const MUSIC_ROUTES4                        ; 1e
	const MUSIC_TRICK_HOUSE_RSE                ; 1f
	const MUSIC_POKE_FLUTE_CHANNEL             ; 20 ; TODO: adapt pokered's SFX_POKEFLUTE
	const MUSIC_MEET_MALE_TRAINER              ; 21
	const MUSIC_GYM_LEADER_BATTLE              ; 22
	const MUSIC_DEFEATED_GYM_LEADER            ; 23
	const MUSIC_BIKE_RIDING                    ; 24
	const MUSIC_LAVENDER                       ; 25
	const MUSIC_POKEMON_TOWER                  ; 26
	const MUSIC_CELADON                        ; 27
	const MUSIC_CANALAVE_CITY_DPPT             ; 28
	const MUSIC_GAME_CORNER                    ; 29
	const MUSIC_MEET_EVIL_TRAINER              ; 2a
	const MUSIC_ROCKET_BATTLE                  ; 2b
	const MUSIC_DUNGEON1                       ; 2c
	const MUSIC_SILPH_CO                       ; 2d
	const MUSIC_SURFING                        ; 2e
	const MUSIC_CINNABAR                       ; 2f
	const MUSIC_CINNABAR_MANSION               ; 30
	const MUSIC_SAFARI_ZONE                    ; 31
	const MUSIC_WILD_BATTLE_GO                 ; 32
	const MUSIC_SURFING_PIKACHU                ; 33
	const MUSIC_INDIGO_PLATEAU                 ; 34
	const MUSIC_FINAL_BATTLE                   ; 35
	const MUSIC_HALL_OF_FAME                   ; 36
	const MUSIC_CREDITS                        ; 37
	const MUSIC_BATTLE_TOWER_THEME             ; 38
	const MUSIC_BATTLE_TOWER_LOBBY             ; 39
	const MUSIC_TRAINER_BATTLE_BW              ; 3a
	const MUSIC_FRONTIER_BRAIN_BATTLE_RSE      ; 3b
	const MUSIC_NEW_BARK_TOWN                  ; 3c
	const MUSIC_PROF_ELM                       ; 3d
	const MUSIC_ROUTE_29                       ; 3e
	const MUSIC_JOHTO_WILD_BATTLE              ; 3f
	const MUSIC_JOHTO_WILD_BATTLE_NIGHT        ; 40
	const MUSIC_CHERRYGROVE_CITY               ; 41
	const MUSIC_ROUTE_30                       ; 42
	const MUSIC_VIOLET_CITY                    ; 43
	const MUSIC_SPROUT_TOWER                   ; 44
	const MUSIC_SAGE_ENCOUNTER                 ; 45
	const MUSIC_JOHTO_TRAINER_BATTLE           ; 46
	const MUSIC_UNION_CAVE                     ; 47
	const MUSIC_RUINS_OF_ALPH                  ; 48
	const MUSIC_HIKER_ENCOUNTER                ; 49
	const MUSIC_AZALEA_TOWN                    ; 4a
	const MUSIC_ROUTE_36                       ; 4b
	const MUSIC_GOLDENROD_CITY                 ; 4c
	const MUSIC_POKECOM_CENTER                 ; 4d
	const MUSIC_BEAUTY_ENCOUNTER               ; 4e
	const MUSIC_JOHTO_GYM_LEADER_BATTLE        ; 4f
	const MUSIC_FINAL_POKEMON_BW               ; 50
	const MUSIC_OFFICER_ENCOUNTER              ; 51
	const MUSIC_NATIONAL_PARK                  ; 52
	const MUSIC_BUG_CATCHING_CONTEST           ; 53
	const MUSIC_BUG_CATCHING_CONTEST_RANKING   ; 54
	const MUSIC_ECRUTEAK_CITY                  ; 55
	const MUSIC_DANCING_HALL                   ; 56
	const MUSIC_KIMONO_ENCOUNTER               ; 57
	const MUSIC_BURNED_TOWER                   ; 58
	const MUSIC_ROUTE_37                       ; 59
	const MUSIC_LIGHTHOUSE                     ; 5a
	const MUSIC_CIANWOOD_CITY_HGSS             ; 5b
	const MUSIC_ROUTE_47_HGSS                  ; 5c
	const MUSIC_SAFARI_ZONE_GATE_HGSS          ; 5d
	const MUSIC_LAKE_OF_RAGE                   ; 5e
	const MUSIC_POKEMANIAC_ENCOUNTER           ; 5f
	const MUSIC_DARK_CAVE                      ; 60
	const MUSIC_DRAGONS_DEN                    ; 61
	const MUSIC_TIN_TOWER                      ; 62
	const MUSIC_ROUTE_26                       ; 63
	const MUSIC_SCARY_HOUSE_XY                 ; 64
	const MUSIC_POWER_PLANT_XY                 ; 65
	const MUSIC_ETERNA_FOREST_DPPT             ; 66
	const MUSIC_MOUNT_CHIMNEY_RSE              ; 67
	const MUSIC_MOUNT_PYRE_RSE                 ; 68
	const MUSIC_ROUTE_205_DPPT                 ; 69
	const MUSIC_WILD_BATTLE_SM                 ; 6a
	const MUSIC_SUNYSHORE_CITY_DPPT            ; 6b
	const MUSIC_TRAINER_BATTLE_SM              ; 6c
	const MUSIC_ROUTE_203_DPPT                 ; 6d
	const MUSIC_WHITE_TREEHOLLOW_W2            ; 6e
	const MUSIC_LAVERRE_CITY_XY                ; 6f
	const MUSIC_ROUTE_101_RSE                  ; 70
	const MUSIC_EVER_GRANDE_CITY_RSE           ; 71
	const MUSIC_OREBURGH_GATE_DPPT             ; 72
	const MUSIC_ROUTE_12_BW                    ; 73
	const MUSIC_ROAD_TO_REVERSAL_MOUNTAIN_B2W2 ; 74
	const MUSIC_LUGIAS_SONG_2000               ; 75
	const MUSIC_LUGIA_BATTLE_HGSS              ; 76
	const MUSIC_SUMMONING_DANCE_HGSS           ; 77
	const MUSIC_HO_OH_BATTLE_HGSS              ; 78
	const MUSIC_MEWTWO_BATTLE_STADIUM          ; 79
	const MUSIC_ABANDONED_SHIP_RSE             ; 7a
	const MUSIC_KANTO_LEGEND_BATTLE_XY         ; 7b
	const MUSIC_SUICUNE_BATTLE                 ; 7c
	const MUSIC_GYM_LEADER_BATTLE_RSE          ; 7d
NUM_SONGS EQU const_value
