; see data/events/npc_trades.asm:NPCTrades
	const_def
	const TRADE_WITH_TAYLOR_FOR_NIDORINA   ; 0
	const TRADE_WITH_CALVIN_FOR_SNEASEL    ; 1
	const TRADE_WITH_BOB_FOR_TOGEPI        ; 2
	const TRADE_WITH_SALLY_FOR_SEEL        ; 3
	const TRADE_WITH_ALICE_FOR_FARFETCHD   ; 4
	const TRADE_WITH_JAKE_FOR_LICKITUNG    ; 5
	const TRADE_WITH_RALPH_FOR_JYNX        ; 6
	const TRADE_WITH_DWAYNE_FOR_MISDREAVUS ; 7
	const TRADE_WITH_CHRISTY_FOR_TANGELA   ; 8
	const TRADE_WITH_ROSS_FOR_HOUNDOUR     ; 9
	
NUM_NPC_TRADES EQU const_value +- 1

; Trade struct
TRADE_DIALOG      EQU 0
TRADE_GIVEMON     EQU 1
TRADE_GETMON      EQU 2
TRADE_NICK        EQU 3
TRADE_DVS         EQU 14
TRADE_PERSONALITY EQU 17
TRADE_BALL        EQU 19
TRADE_ITEM        EQU 20
TRADE_OT_ID       EQU 22
TRADE_OT_NAME     EQU 23

; Trade dialogs
TRADE_INTRO    EQU 0
TRADE_CANCEL   EQU 1
TRADE_WRONG    EQU 2
TRADE_COMPLETE EQU 3
TRADE_AFTER    EQU 4
