	const_def
	const PHONE_00
	const PHONE_MOM
	const PHONE_OAK
	const PHONE_BILL

	const_def
	const SPECIALCALL_NONE
	const SPECIALCALL_POKERUS

	const_def
	const PHONE_CONTACT_TRAINER_CLASS
	const PHONE_CONTACT_TRAINER_NUMBER
	const PHONE_CONTACT_MAP_GROUP
	const PHONE_CONTACT_MAP_NUMBER
	const PHONE_CONTACT_SCRIPT1_TIME
	const PHONE_CONTACT_SCRIPT1_BANK
	const PHONE_CONTACT_SCRIPT1_ADDR_LO
	const PHONE_CONTACT_SCRIPT1_ADDR_HI
	const PHONE_CONTACT_SCRIPT2_TIME
	const PHONE_CONTACT_SCRIPT2_BANK
	const PHONE_CONTACT_SCRIPT2_ADDR_LO
	const PHONE_CONTACT_SCRIPT2_ADDR_HI
PHONE_TABLE_WIDTH EQU const_value
CONTACT_LIST_SIZE EQU 30

; mom items
const_value = 1
	const MOM_ITEM
	const MOM_DOLL
