; sprites
	const_def
	const SPRITE_NONE
	const SPRITE_RED
	const SPRITE_RED_BIKE
	const SPRITE_RED_SURF
	const SPRITE_LEAF
	const SPRITE_LEAF_BIKE
	const SPRITE_LEAF_SURF

SPRITE_POKEMON EQU const_value

	const SPRITE_DAYCARE_MON_1
	const SPRITE_DAYCARE_MON_2
	const SPRITE_GROTTO_MON

SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE
	const SPRITE_DOLL_1
	const SPRITE_DOLL_2
	const SPRITE_BIG_DOLL
