	const_def 1
; These tilesets share the first 160 tiles and the first 148 metatiles
	const TILESET_PALLET_CINNABAR
	const TILESET_VIRIDIAN ; does not share all metatiles
	const TILESET_PEWTER
	const TILESET_CERULEAN ; does not share all metatiles
	const TILESET_VERMILION
	const TILESET_CELADON
	const TILESET_LAVENDER
	const TILESET_CYCLING_ROAD
	const TILESET_FUCHSIA
	const TILESET_SAFFRON
	const TILESET_INDIGO ; does not share metatiles
	const TILESET_FOREST ; does not share metatiles
GENERIC_KANTO_GFX EQU const_value
	const TILESET_NEW_BARK_CHERRYGROVE
	const TILESET_VIOLET_MAHOGANY
	const TILESET_AZALEA_BLACKTHORN ; does not share all metatiles
	const TILESET_GOLDENROD
	const TILESET_ECRUTEAK ; does not share all metatiles
	const TILESET_OLIVINE_CIANWOOD ; does not share all metatiles
	const TILESET_BATTLE_TOWER_OUTSIDE
	const TILESET_NATIONAL_PARK
	const TILESET_SHRINES_RUINS_OUTSIDE
GENERIC_GFX EQU const_value
; These are independent tilesets
	const TILESET_SAFARI_ZONE
	const TILESET_POKECENTER
	const TILESET_LAB
	const TILESET_SHRINES_RUINS
	const TILESET_CAVE
	;------------------------------------
	const TILESET_PC_SHAMOUTI_ISLAND
	const TILESET_PC_VALENCIA_ISLAND
	const TILESET_PC_FARAWAY_ISLAND
	const TILESET_PC_JOHTO_HOUSE
	const TILESET_PC_KANTO_HOUSE
	const TILESET_PC_TRADITIONAL_HOUSE
	const TILESET_PC_MART
	const TILESET_PC_GATE
	const TILESET_PC_GYM
	const TILESET_PC_MAGNET_TRAIN
	const TILESET_PC_CHAMPIONS_ROOM
	const TILESET_PC_PORT
	const TILESET_PC_LAB
	const TILESET_PC_FACILITY
	const TILESET_PC_CELADON_MANSION
	const TILESET_PC_GAME_CORNER
	const TILESET_PC_HOME_DECOR_STORE
	const TILESET_PC_MUSEUM
	const TILESET_PC_HOTEL
	const TILESET_PC_SPROUT_TOWER
	const TILESET_PC_BATTLE_TOWER_INSIDE
	const TILESET_PC_RADIO_TOWER
	const TILESET_PC_LIGHTHOUSE
	const TILESET_PC_UNDERGROUND
	const TILESET_PC_CAVE
	const TILESET_PC_QUIET_CAVE
	const TILESET_PC_ICE_PATH
	const TILESET_PC_TUNNEL
	const TILESET_PC_FOREST
	const TILESET_PC_RUINS_OF_ALPH
	const TILESET_PC_POKEMON_MANSION

	const_def
	const PAL_BG_GRAY   ; 0
	const PAL_BG_RED    ; 1
	const PAL_BG_GREEN  ; 2
	const PAL_BG_WATER  ; 3
	const PAL_BG_YELLOW ; 4
	const PAL_BG_BROWN  ; 5
	const PAL_BG_ROOF   ; 6
	const PAL_BG_TEXT   ; 7

	const_def $80
	const PAL_BG_PRIORITY_GRAY   ; 80
	const PAL_BG_PRIORITY_RED    ; 81
	const PAL_BG_PRIORITY_GREEN  ; 82
	const PAL_BG_PRIORITY_WATER  ; 83
	const PAL_BG_PRIORITY_YELLOW ; 84
	const PAL_BG_PRIORITY_BROWN  ; 85
	const PAL_BG_PRIORITY_ROOF   ; 86
	const PAL_BG_PRIORITY_TEXT   ; 87
