	const_def 1
	const TILESET_PC_JOHTO_TRADITIONAL    ; 01
	const TILESET_PC_JOHTO_MODERN         ; 02
	const TILESET_PC_BATTLE_TOWER_OUTSIDE ; 03
	const TILESET_PC_JOHTO_OVERCAST       ; 04
	const TILESET_PC_KANTO                ; 05
	const TILESET_PC_INDIGO_PLATEAU       ; 06
	const TILESET_PC_SHAMOUTI_ISLAND      ; 07
	const TILESET_PC_VALENCIA_ISLAND      ; 08
	const TILESET_PC_FARAWAY_ISLAND       ; 09
	const TILESET_PC_JOHTO_HOUSE          ; 0a
	const TILESET_PC_KANTO_HOUSE          ; 0b
	const TILESET_PC_TRADITIONAL_HOUSE    ; 0c
	const TILESET_PC_POKECENTER           ; 0d
	const TILESET_PC_POKECOM_CENTER       ; 0e
	const TILESET_PC_MART                 ; 0f
	const TILESET_PC_GATE                 ; 10
	const TILESET_PC_GYM                  ; 11
	const TILESET_PC_MAGNET_TRAIN         ; 12
	const TILESET_PC_CHAMPIONS_ROOM       ; 13
	const TILESET_PC_PORT                 ; 14
	const TILESET_PC_LAB                  ; 15
	const TILESET_PC_FACILITY             ; 16
	const TILESET_PC_CELADON_MANSION      ; 17
	const TILESET_PC_GAME_CORNER          ; 18
	const TILESET_PC_HOME_DECOR_STORE     ; 19
	const TILESET_PC_MUSEUM               ; 1a
	const TILESET_PC_HOTEL                ; 1b
	const TILESET_PC_SPROUT_TOWER         ; 1c
	const TILESET_PC_BATTLE_TOWER_INSIDE  ; 1d
	const TILESET_PC_RADIO_TOWER          ; 1e
	const TILESET_PC_LIGHTHOUSE           ; 1f
	const TILESET_PC_UNDERGROUND          ; 20
	const TILESET_PC_CAVE                 ; 21
	const TILESET_PC_QUIET_CAVE           ; 22
	const TILESET_PC_ICE_PATH             ; 23
	const TILESET_PC_TUNNEL               ; 24
	const TILESET_PC_FOREST               ; 25
	const TILESET_PC_PARK                 ; 26
	const TILESET_PC_SAFARI_ZONE          ; 27
	const TILESET_PC_RUINS_OF_ALPH        ; 28
	const TILESET_PC_ALPH_WORD_ROOM       ; 29
	const TILESET_PC_POKEMON_MANSION      ; 2a

	const_def
	const PAL_BG_GRAY   ; 0
	const PAL_BG_RED    ; 1
	const PAL_BG_GREEN  ; 2
	const PAL_BG_WATER  ; 3
	const PAL_BG_YELLOW ; 4
	const PAL_BG_BROWN  ; 5
	const PAL_BG_ROOF   ; 6
	const PAL_BG_TEXT   ; 7

	const_def $80
	const PAL_BG_PRIORITY_GRAY   ; 80
	const PAL_BG_PRIORITY_RED    ; 81
	const PAL_BG_PRIORITY_GREEN  ; 82
	const PAL_BG_PRIORITY_WATER  ; 83
	const PAL_BG_PRIORITY_YELLOW ; 84
	const PAL_BG_PRIORITY_BROWN  ; 85
	const PAL_BG_PRIORITY_ROOF   ; 86
	const PAL_BG_PRIORITY_TEXT   ; 87
