Music:
	dba Music_Nothing
	dba Music_IntroBattle
	dba Music_RBYTitleScreen
	dba Music_RBYPalletTown
	dba Music_MeetProfOak
	dba Music_OaksLab
	dba Music_MeetRival
	dba Music_FarewellRival
	dba Music_Routes1
	dba Music_WildBattle
	dba Music_DefeatedWildMon
	dba Music_SuccessfulCapture
	dba Music_Cities1
	dba Music_Pokecenter
	dba Music_PkmnHealed
	dba Music_Dungeon2
	dba Music_MuseumGuy
	dba Music_MeetFemaleTrainer
	dba Music_TrainerBattle
	dba Music_DefeatedTrainer
	dba Music_Dungeon3
	dba Music_MeetJessieJames
	dba Music_MtMoonSquare
	dba Music_Routes3
	dba Music_Cities2
	dba Music_RBYGym
	dba Music_Routes2
	dba Music_JigglypuffSong
	dba Music_Vermilion
	dba Music_SSAnne
	dba Music_Routes4
	dba Music_TrickHouseRSE
	dba Music_PokeFluteChannel
	dba Music_MeetMaleTrainer
	dba Music_GymLeaderBattle
	dba Music_DefeatedGymLeader
	dba Music_BikeRiding
	dba Music_Lavender
	dba Music_PokemonTower
	dba Music_Celadon
	dba Music_CanalaveCityDPPt
	dba Music_RBYGameCorner
	dba Music_MeetEvilTrainer
	dba Music_RocketBattle
	dba Music_Dungeon1
	dba Music_SilphCo
	dba Music_Surfing
	dba Music_Cinnabar
	dba Music_CinnabarMansion
	dba Music_SafariZone
	dba Music_WildBattleGo
	dba Music_SurfingPikachu
	dba Music_RBYIndigoPlateau
	dba Music_FinalBattle
	dba Music_RBYHallOfFame
	dba Music_RBYCredits
	dba Music_BattleTowerTheme
	dba Music_BattleTowerLobby
	dba Music_TrainerBattleBW
	dba Music_FrontierBrainBattleRSE
	dba Music_NewBarkTown
	dba Music_ElmsLab
	dba Music_Route29
	dba Music_JohtoWildBattle
	dba Music_JohtoWildBattleNight
	dba Music_CherrygroveCity
	dba Music_Route30
	dba Music_VioletCity
	dba Music_SproutTower
	dba Music_LookSage
	dba Music_JohtoTrainerBattle
	dba Music_UnionCave
	dba Music_RuinsOfAlphInterior
	dba Music_LookHiker
	dba Music_AzaleaTown
	dba Music_Route36
	dba Music_GoldenrodCity
	dba Music_PokeComCenter
	dba Music_LookBeauty
	dba Music_JohtoGymBattle
	dba Music_FinalPokemonBW
	dba Music_LookOfficer
	dba Music_NationalPark
	dba Music_BugCatchingContest
	dba Music_ContestResults
	dba Music_EcruteakCity
	dba Music_DancingHall
	dba Music_LookKimonoGirl
	dba Music_BurnedTower
	dba Music_Route37
	dba Music_Lighthouse
	dba Music_CianwoodCityHGSS
	dba Music_Route47HGSS
	dba Music_SafariZoneGateHGSS
	dba Music_LakeOfRage
	dba Music_LookPokemaniac
	dba Music_DarkCave
	dba Music_DragonsDen
	dba Music_TinTower
	dba Music_Route26
	dba Music_ScaryHouseXY
	dba Music_PowerPlantXY
	dba Music_EternaForestDPPt
	dba Music_MountChimneyRSE
	dba Music_MountPyreRSE
	dba Music_Route205DPPt
	dba Music_WildBattleSM
	dba Music_SunyshoreCityDPPt
	dba Music_TrainerBattleSM
	dba Music_Route203DPPt
	dba Music_WhiteTreehollowWhite2
	dba Music_LaverreCityXY
	dba Music_Route101RSE
	dba Music_EverGrandeCityRSE
	dba Music_OreburghGateDPPt
	dba Music_Route12BW
	dba Music_RoadToReversalMountainB2W2
	dba Music_LugiasSong2000
	dba Music_LugiaBattleHGSS
	dba Music_SummoningDanceHGSS
	dba Music_HoOhBattleHGSS
	dba Music_MewtwoBattleStadium
	dba Music_AbandonedShipRSE
	dba Music_KantoLegendBattleXY
	dba Music_SuicuneBattle
	dba Music_GymLeaderBattleRSE
