Route4_MapScriptHeader:
	db 0 ; scene scripts

	db 0 ; callbacks

	db 2 ; warp events
	warp_event  4,  7, MOUNT_MOON_B1F, 8
	warp_event 19,  5, MOUNT_MOON_SQUARE, 1 ; TODO: Cable Car Building

	db 0 ; coord events

	db 0 ; bg events

	db 8 ; object events
	object_event 12,  0, SPRITE_CABLE_CAR_POLE, SPRITEMOVEDATA_CABLE_LARGE, 0, 0, -1, -1, PAL_NPC_ROCK, PERSONTYPE_COMMAND, end, NULL, -1
	object_event 13,  2, SPRITE_CABLE_CAR_POLE, SPRITEMOVEDATA_CABLE_SMALL, 0, 0, -1, -1, PAL_NPC_ROCK, PERSONTYPE_COMMAND, end, NULL, -1
	object_event 14,  2, SPRITE_CABLE_CAR_POLE, SPRITEMOVEDATA_CABLE_LARGE, 0, 0, -1, -1, PAL_NPC_ROCK, PERSONTYPE_COMMAND, end, NULL, -1
	object_event 15,  4, SPRITE_CABLE_CAR_POLE, SPRITEMOVEDATA_CABLE_SMALL, 0, 0, -1, -1, PAL_NPC_ROCK, PERSONTYPE_COMMAND, end, NULL, -1
	object_event 17,  4, SPRITE_CABLE_CAR_POLE, SPRITEMOVEDATA_CABLE_SIDE, 0, 0, -1, -1, PAL_NPC_ROCK, PERSONTYPE_COMMAND, end, NULL, -1
	object_event 16,  4, SPRITE_CABLE_CAR_POLE, SPRITEMOVEDATA_OVERHEAD_TILE_DOWN, 0, 0, -1, -1, PAL_NPC_ROCK, PERSONTYPE_COMMAND, end, NULL, -1
	object_event 16,  5, SPRITE_CABLE_CAR_POLE, SPRITEMOVEDATA_TILE_UP, 0, 0, -1, -1, PAL_NPC_ROCK, PERSONTYPE_COMMAND, end, NULL, -1
	fruittree_event 37,  6, FRUITTREE_ROUTE_4, ORAN_BERRY

	const_def 1 ; object constants
