PikachuAnimationExtraPointers:
	dw PikachuPlainAnimationExtra
	dw PikachuFlyAnimationExtra
	dw PikachuSurfAnimationExtra
	dw PikachuPikaAnimationExtra
	dw PikachuChuchuAnimationExtra

ArbokAnimationExtraPointers:
	dw ArbokJohtoAnimationExtra
	dw ArbokKantoAnimationExtra
	dw ArbokKogaAnimationExtra
	dw ArbokAgathaAnimationExtra
	dw ArbokArianaAnimationExtra

MagikarpAnimationExtraPointers:
	dw MagikarpPlainAnimationExtra
	dw MagikarpSkellyAnimationExtra
	dw MagikarpCalico1AnimationExtra
	dw MagikarpCalico2AnimationExtra
	dw MagikarpCalico3AnimationExtra
	dw MagikarpTwoToneAnimationExtra
	dw MagikarpOrcaAnimationExtra
	dw MagikarpDapplesAnimationExtra
	dw MagikarpTigerAnimationExtra
	dw MagikarpZebraAnimationExtra
	dw MagikarpStripeAnimationExtra
	dw MagikarpBubblesAnimationExtra
	dw MagikarpForeheadAnimationExtra
	dw MagikarpMaskAnimationExtra

GyaradosAnimationExtraPointers:
rept NUM_MAGIKARP
	dw GyaradosPlainAnimationExtra
endr
	dw GyaradosRedAnimationExtra

MewtwoAnimationExtraPointers:
	dw MewtwoPlainAnimationExtra
	dw MewtwoArmoredAnimationExtra
