PikachuPlainBitmasks:  INCLUDE "gfx/pokemon/pikachu_plain/bitmask.asm"
PikachuFlyBitmasks:    INCLUDE "gfx/pokemon/pikachu_fly/bitmask.asm"
PikachuSurfBitmasks:   INCLUDE "gfx/pokemon/pikachu_surf/bitmask.asm"
PikachuPikaBitmasks:   INCLUDE "gfx/pokemon/pikachu_pika/bitmask.asm"
PikachuChuchuBitmasks: INCLUDE "gfx/pokemon/pikachu_chuchu/bitmask.asm"

ArbokJohtoBitmasks:  INCLUDE "gfx/pokemon/arbok_johto/bitmask.asm"
ArbokKantoBitmasks:  INCLUDE "gfx/pokemon/arbok_kanto/bitmask.asm"
ArbokKogaBitmasks:   INCLUDE "gfx/pokemon/arbok_koga/bitmask.asm"
ArbokAgathaBitmasks: INCLUDE "gfx/pokemon/arbok_agatha/bitmask.asm"
ArbokArianaBitmasks: INCLUDE "gfx/pokemon/arbok_ariana/bitmask.asm"

MagikarpPlainBitmasks:    INCLUDE "gfx/pokemon/magikarp_plain/bitmask.asm"
MagikarpSkellyBitmasks:   INCLUDE "gfx/pokemon/magikarp_skelly/bitmask.asm"
MagikarpCalico1Bitmasks:  INCLUDE "gfx/pokemon/magikarp_calico1/bitmask.asm"
MagikarpCalico2Bitmasks:  INCLUDE "gfx/pokemon/magikarp_calico2/bitmask.asm"
MagikarpCalico3Bitmasks:  INCLUDE "gfx/pokemon/magikarp_calico3/bitmask.asm"
MagikarpTwoToneBitmasks:  INCLUDE "gfx/pokemon/magikarp_twotone/bitmask.asm"
MagikarpOrcaBitmasks:     INCLUDE "gfx/pokemon/magikarp_orca/bitmask.asm"
MagikarpDapplesBitmasks:  INCLUDE "gfx/pokemon/magikarp_dapples/bitmask.asm"
MagikarpTigerBitmasks:    INCLUDE "gfx/pokemon/magikarp_tiger/bitmask.asm"
MagikarpZebraBitmasks:    INCLUDE "gfx/pokemon/magikarp_zebra/bitmask.asm"
MagikarpStripeBitmasks:   INCLUDE "gfx/pokemon/magikarp_stripe/bitmask.asm"
MagikarpBubblesBitmasks:  INCLUDE "gfx/pokemon/magikarp_bubbles/bitmask.asm"
MagikarpForeheadBitmasks: INCLUDE "gfx/pokemon/magikarp_forehead/bitmask.asm"
MagikarpMaskBitmasks:     INCLUDE "gfx/pokemon/magikarp_mask/bitmask.asm"

GyaradosPlainBitmasks: INCLUDE "gfx/pokemon/gyarados_plain/bitmask.asm"
GyaradosRedBitmasks:   INCLUDE "gfx/pokemon/gyarados_red/bitmask.asm"

MewtwoPlainBitmasks:   INCLUDE "gfx/pokemon/mewtwo_plain/bitmask.asm"
MewtwoArmoredBitmasks: INCLUDE "gfx/pokemon/mewtwo_armored/bitmask.asm"
