RGB_MONOCHROME_WHITE EQUS "RGB 31, 31, 31"
RGB_MONOCHROME_LIGHT EQUS "RGB 31, 16, 16"
RGB_MONOCHROME_DARK  EQUS "RGB 18, 07, 07"
RGB_MONOCHROME_BLACK EQUS "RGB 03, 02, 02"

PAL_MONOCHROME_WHITE EQU (palred 31 + palgreen 31 + palblue 31)
PAL_MONOCHROME_BLACK EQU (palred 03 + palgreen 02 + palblue 02)


MONOCHROME_RGB_FOUR: macro
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
endm

MONOCHROME_RGB_FOUR_NIGHT: macro
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
endm

MONOCHROME_RGB_FOUR_DARKNESS: macro
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
endm

MONOCHROME_RGB_FOUR_OW: macro
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_BLACK
endm

MONOCHROME_RGB_FOUR_OW_NIGHT: macro
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
endm

MONOCHROME_RGB_FOUR_OW_DARKNESS: macro
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
endm

MONOCHROME_RGB_TWO: macro
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
endm

MONOCHROME_RGB_TWO_NIGHT: macro
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
endm
