LyingOldManSprite:     INCBIN "gfx/sprites/lying_old_man.2bpp"
BoulderSprite:         INCBIN "gfx/sprites/boulder.2bpp"
PaperSheetSprite:      INCBIN "gfx/sprites/paper_sheet.2bpp"
BookMapDexSprite:      INCBIN "gfx/sprites/book_map_dex.2bpp"
ClipboardSprite:       INCBIN "gfx/sprites/clipboard.2bpp"
OldAmberSprite:        INCBIN "gfx/sprites/old_amber.2bpp"
PokedexSprite:         INCBIN "gfx/sprites/pokedex.2bpp"
TownMapSprite:         INCBIN "gfx/sprites/map_ow.2bpp"
BerryTreeSprite:       INCBIN "gfx/sprites/berry_tree.2bpp"
BagOverworldSprite:    INCBIN "gfx/sprites/bag.2bpp"
BallSprite:            INCBIN "gfx/sprites/ball.2bpp"
OmanyteSprite:         INCBIN "gfx/sprites/omanyte.2bpp"
FossilSprite:          INCBIN "gfx/sprites/fossil.2bpp"
SudowoodoSprite:       INCBIN "gfx/sprites/sudowoodo.2bpp"
SlowpokeOverworld:     INCBIN "gfx/sprites/pokey.2bpp"
DittoOverworld:        INCBIN "gfx/sprites/ditto.2bpp"
SnorlaxSprite:         INCBIN "gfx/sprites/snorlax.2bpp"
CelebiSprite:          INCBIN "gfx/sprites/celebi.2bpp"

SurfingPikachu:        INCBIN "gfx/sprites/surfing_pikachu.2bpp"
SeelSprite:            INCBIN "gfx/sprites/seel.2bpp"
SlowbroSprite:         INCBIN "gfx/sprites/slowbro.2bpp"

BirdSprite:            INCBIN "gfx/sprites/bird.2bpp"
ClefairySprite:        INCBIN "gfx/sprites/clefairy.2bpp"

BrockOverworld:        INCBIN "gfx/sprites/brock.2bpp"
MistyOverworld:        INCBIN "gfx/sprites/misty.2bpp"
SurgeOverworld:        INCBIN "gfx/sprites/surge.2bpp"
ErikaSprite:           INCBIN "gfx/sprites/erika.2bpp"
SabrinaOverworld:      INCBIN "gfx/sprites/sabrina.2bpp"
KogaOverworld:         INCBIN "gfx/sprites/koga.2bpp"
BlaineOverworld:       INCBIN "gfx/sprites/blaine.2bpp"
GiovanniSprite:        INCBIN "gfx/sprites/giovanni.2bpp"

BrendanOverworld:      INCBIN "gfx/sprites/brendan.2bpp"
FlanneryOverworld:     INCBIN "gfx/sprites/flannery.2bpp"
LookerOverworld:       INCBIN "gfx/sprites/tennant.2bpp"
GreeterWoman:          INCBIN "gfx/sprites/greeter_woman.2bpp"
SwimmerFSprite:        INCBIN "gfx/sprites/swimmer_f.2bpp"
OfficerJennySprite:    INCBIN "gfx/sprites/officer_jenny.2bpp"
JessieSprite:          INCBIN "gfx/sprites/jessie.2bpp"
JamesSprite:           INCBIN "gfx/sprites/james.2bpp"
HiroSprite:            INCBIN "gfx/sprites/hiro.2bpp"
KrisSprite:            INCBIN "gfx/sprites/kris.2bpp"
SilverSprite:          INCBIN "gfx/sprites/silver.2bpp"
